# Generated by Django 2.2.4 on 2019-08-20 12:33

from django.db import migrations, models
import src.api.helpers.colors


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default=src.api.helpers.colors.generate_random_color, help_text='Default color associated with this product.', max_length=255),
        ),
        migrations.AddField(
            model_name='revenuestream',
            name='color',
            field=models.CharField(blank=True, default=src.api.helpers.colors.generate_random_color, help_text='Default color associated with this revenue stream.', max_length=255),
        ),
    ]
