# Generated by Django 2.2.4 on 2019-08-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receipt_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
