# Generated by Django 2.2.4 on 2019-08-14 21:58

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190814_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueTypeOKR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False, help_text='This is to make sure deletes are not actual deletes')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('period', models.CharField(max_length=100)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Metric')),
                ('revenue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='okrs', to='api.RevenueType')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RevenueStreamOKR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False, help_text='This is to make sure deletes are not actual deletes')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('period', models.CharField(max_length=100)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Metric')),
                ('revenue_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='okrs', to='api.RevenueStream')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentOKR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False, help_text='This is to make sure deletes are not actual deletes')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('period', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='okrs', to='api.Department')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Metric')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
    ]
