# Generated by Django 2.2.4 on 2019-08-21 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190820_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomestream',
            name='revenue_stream',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='income_streams', to='api.RevenueStream'),
            preserve_default=False,
        ),
    ]
