# Generated by Django 2.2.4 on 2019-08-11 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_incomestreamokr_productokr_valuecentreokr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productokr',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='okrs', to='api.Product'),
        ),
        migrations.AlterField(
            model_name='valuecentreokr',
            name='value_centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='okrs', to='api.ValueCentre'),
        ),
    ]
