# Generated by Django 2.2.4 on 2019-08-16 07:53

from django.db import migrations, models
import src.api.helpers.colors


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_departmentokr_revenuestreamokr_revenuetypeokr'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuecentre',
            name='color',
            field=models.CharField(blank=True, default=src.api.helpers.colors.generate_random_color, help_text='Default color associated with this value centre. Important for display in graphical representations.', max_length=255),
        ),
    ]
