# Generated by Django 2.2.4 on 2019-08-21 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_incomestream_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='end',
        ),
        migrations.RemoveField(
            model_name='period',
            name='start',
        ),
        migrations.AlterField(
            model_name='incomestreamtarget',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_streams', to='api.Period'),
        ),
        migrations.AlterField(
            model_name='period',
            name='period_type',
            field=models.CharField(choices=[('quarterly', 'Quaterly'), ('monthly', 'Monthly')], db_index=True, max_length=30),
        ),
    ]
