# Generated by Django 2.2.4 on 2019-08-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190811_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomestreamtarget',
            name='end',
            field=models.CharField(default='placeholder', max_length=100),
        ),
        migrations.AddField(
            model_name='incomestreamtarget',
            name='start',
            field=models.CharField(default='placeholder', max_length=100),
        ),
        migrations.AddField(
            model_name='producttarget',
            name='end',
            field=models.CharField(default='placeholder', max_length=100),
        ),
        migrations.AddField(
            model_name='producttarget',
            name='start',
            field=models.CharField(default='placeholder', max_length=100),
        ),
        migrations.AddField(
            model_name='valuecentretarget',
            name='end',
            field=models.CharField(default='placeholder', max_length=100),
        ),
        migrations.AddField(
            model_name='valuecentretarget',
            name='start',
            field=models.CharField(default='placeholder', max_length=100),
        ),
    ]
