# Generated by Django 2.2.4 on 2019-08-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_incomestream_revenue_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='revenue_stream',
        ),
    ]
