# Generated by Django 2.2.4 on 2019-08-21 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_transaction_revenue_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='income_stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.IncomeStream'),
        ),
    ]
