# Generated by Django 2.2.4 on 2019-08-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190821_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='year',
            field=models.CharField(choices=[('2019', '2019'), ('2020', '2020')], db_index=True, default='2019', max_length=30),
        ),
    ]
