# Generated by Django 2.2.4 on 2019-08-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190813_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomestreamokr',
            name='period',
            field=models.CharField(default='placeholder', max_length=100),
        ),
        migrations.AddField(
            model_name='productokr',
            name='period',
            field=models.CharField(default='placeholder', max_length=100),
        ),
        migrations.AddField(
            model_name='valuecentreokr',
            name='period',
            field=models.CharField(default='placeholder', max_length=100),
        ),
    ]
