# Generated by Django 2.2.4 on 2019-08-22 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190822_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomestreamtarget',
            name='name',
        ),
        migrations.RemoveField(
            model_name='producttarget',
            name='name',
        ),
        migrations.RemoveField(
            model_name='revenuestreamtarget',
            name='name',
        ),
        migrations.RemoveField(
            model_name='valuecentretarget',
            name='name',
        ),
        migrations.AlterField(
            model_name='incomestreamtarget',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_streams', to='api.Metric'),
        ),
    ]
