# Generated by Django 2.2.4 on 2019-08-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190822_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomestreamtarget',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producttarget',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='revenuestreamtarget',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valuecentretarget',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
