# Generated by Django 2.2.4 on 2019-08-29 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190822_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomestream',
            name='revenue_stream',
            field=models.ForeignKey(help_text='The revenue stream e.g embu with this income stream', on_delete=django.db.models.deletion.CASCADE, related_name='income_streams', to='api.RevenueStream'),
        ),
        migrations.AlterField(
            model_name='producttarget',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='api.Metric'),
        ),
        migrations.AlterField(
            model_name='producttarget',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='api.Period'),
        ),
        migrations.AlterField(
            model_name='revenuestreamtarget',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_streams', to='api.Metric'),
        ),
        migrations.AlterField(
            model_name='revenuestreamtarget',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_streams', to='api.Period'),
        ),
        migrations.AlterField(
            model_name='valuecentretarget',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='value_centres', to='api.Metric'),
        ),
        migrations.AlterField(
            model_name='valuecentretarget',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='value_centres', to='api.Period'),
        ),
    ]
